before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - "which ssh-agent || ( apt-get install -qq openssh-client )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_dev:
    stage: build
    script:
        - ssh $TENCENT_SSH "cd /home/ubuntu/btc-web-client-argon/ && git checkout dev && git pull && npm install && npm run build && cd /home/ubuntu/btc-deployment-infrastructure/ && git checkout main && git pull && chmod +x rebuild.sh && sudo ./rebuild.sh && exit"
    rules:
        - if: $CI_COMMIT_BRANCH == 'dev'
